
import { EditorProject, BuildLessonResult } from "@/lib/scorm/types";

/**
 * Orchestrates the creation of a lesson package using a multi-level AI approach.
 *
 * @param teacherInput The initial input from the teacher (e.g., a simple prompt).
 * @param language The target language for the lesson.
 * @returns A full lesson package with supplementary metadata.
 */
export async function buildLessonPackage(teacherInput: string, language: "en" | "ar"): Promise<BuildLessonResult> {
    console.log(`Orchestrator: Starting lesson build for prompt: "${teacherInput}"`);

    // --- Level 2: Big AI Model ---
    // First, call the LLM to generate the core content and structure of the lesson.
    // This is necessary because we need the content before we can validate or analyze it.
    const generatedProject = await generateLessonFromPrompt(teacherInput, language);

    // Create a complete project structure from the partial data returned by the LLM
    const project: EditorProject = {
        id: `proj-${Date.now()}`,
        title: "Untitled Project",
        version: "1.0",
        theme: { direction: language === 'ar' ? 'rtl' : 'ltr', styles: {} },
        pages: [],
        ...generatedProject, // Override defaults with LLM output
    };
    
    console.log("Orchestrator: Lesson content generated by Level 2 AI.", project);

    // --- Level 0: Rules & Simple Logic ---
    // Now, run validation rules on the generated content.
    const warnings = validateProject(project);
    console.log("Orchestrator: Validation complete. Warnings found:", warnings);

    // --- Level 1: Simple ML Models ---
    // Run predictions and recommendations on the generated content.
    const [predictedDifficulty, recommendedTags] = await Promise.all([
        predictDifficulty(project),
        recommendTags(project)
    ]);
    console.log(`Orchestrator: Level 1 ML predictions - Difficulty: ${predictedDifficulty}, Tags: ${recommendedTags.join(', ')}`);

    // --- Final Combination ---
    // Combine all results into a single, structured response.
    const result: BuildLessonResult = {
        project,
        warnings,
        metadata: {
            predictedDifficulty,
            recommendedTags,
        }
    };

    console.log("Orchestrator: Build complete.");
    return result;
}

// You could add other orchestrator functions here, for example:
// export async function evaluateStudentWriting(submission: string) { ... }
// export async function recommendNextSteps(studentStats: any) { ... }
